### ISSUE TITLE
iPhone SE - iOS 12.1.2 Crashing

### ISSUE THREAD

**Issue by h-o-sein** [GeoSn0w/GeoFilza#10]
On my iPhone SE iOS 12.1.2 , I open the program quickly, and the program will not open and Crash @GeoSn0w
please help me

**Comment by AbandonedCart** [comment]
iPhone 5S (T-Mobile)
12.1.1
GeoFilzaUniversal (Cydia Impactor)

White screen to reboot on first run
White screen only on every subsequent launch

Let me know if you need any logs or other information.

It was my understanding 4K began with iPhone 6, but I doubt that is relevant or perhaps why the iPhone 5S is specifically included in every mention.
